
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql+psycopg2://postgres:123456@db:5432/Todosapp"

      SECRET_KEY: "e5944be1ea9d658a7dca1a52daa154c3844370a765e824127f34e8bf877a2cdc"
      EMAIL_ADDRESS: "luutiendat1811@gmail.com"
      EMAIL_PASSWORD: "dbodaxtewdwhrlmi"
      SMTP_HOST: "smtp.gmail.com"
      SMTP_PORT: "587"


  db:
    image: postgres:13
    environment:
      POSTGRES_DB: Todosapp
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
